name: moonshot
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - archspec=0.2.3=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - boltons=24.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - chardet=5.2.0=py311h38be061_2
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cmake=3.30.5=hf9cb763_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=24.9.2=py311h38be061_0
  - conda-build=24.9.0=py311h38be061_0
  - conda-index=0.5.0=pyhd8ed1ab_0
  - conda-libmamba-solver=24.9.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_0
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - fmt=11.0.2=h434a139_0
  - frozendict=2.4.6=py311h9ecbd09_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipython=8.29.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h38be061_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libarchive=3.7.4=hfca40fe_0
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libcurl=8.10.1=hbbe4b11_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=25_linux64_openblas
  - liblief=0.14.1=h5888daf_2
  - libmamba=1.5.10=hf72d635_1
  - libmambapy=1.5.10=py311h18a8eac_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libsolv=0.7.30=h3509ff9_0
  - libsqlite=3.47.0=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.49.2=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mamba=1.5.10=py311h3072747_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - menuinst=2.1.2=py311h38be061_1
  - more-itertools=10.5.0=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - numpy=2.1.2=py311h71ddf71_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.17.2=h58526e2_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=pyh8b19718_1
  - pkginfo=1.11.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.1.0=py311h9ecbd09_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-lief=0.14.1=py311hfdbb021_2
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h459d7ec_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.10=hc5c86c4_3_cpython
  - python-libarchive-c=5.1=py311h38be061_1
  - python_abi=3.11=5_cp311
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h9ecbd09_1
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.32.3=pyhd8ed1ab_0
  - rhash=1.4.5=hb9d3cd8_0
  - ripgrep=14.1.1=h8fae777_0
  - rpds-py=0.20.0=py311h9e33e62_1
  - ruamel.yaml=0.18.6=py311h9ecbd09_1
  - ruamel.yaml.clib=0.2.8=py311h9ecbd09_1
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - truststore=0.9.2=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zstandard=0.23.0=py311hbc35293_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - alembic==1.14.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - babel==2.16.0
      - bleach==6.2.0
      - blinker==1.9.0
      - colorlog==6.9.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.2.0
      - debugpy==1.8.12
      - defusedxml==0.7.1
      - dill==0.3.8
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - expecttest==0.2.1
      - fastapi==0.115.7
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - flask==3.1.0
      - fonttools==4.55.5
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.13.1
      - gradio-client==1.6.0
      - graycode==1.0.5
      - greenlet==3.1.1
      - grpcio==1.70.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - hydra-core==1.3.2
      - hypothesis==6.115.5
      - imageio==2.37.0
      - ipykernel==6.29.5
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - joblib==1.4.2
      - json5==0.10.0
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-mathjax==0.2.6
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-git==0.50.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lightning-utilities==0.11.9
      - lintrunner==0.12.5
      - mako==1.3.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mistune==3.1.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbdime==4.0.2
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.11.0.86
      - optree==0.13.0
      - optuna==4.2.0
      - orjson==3.10.15
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - pillow==10.2.0
      - prometheus-client==0.21.1
      - propcache==0.2.1
      - protobuf==5.29.3
      - pyarrow==19.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-etcd==0.4.5
      - python-json-logger==3.2.1
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.0.post0
      - pyzmq==26.2.0
      - ray==2.41.0
      - rdkit==2024.9.4
      - regex==2024.11.6
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - ruff==0.9.3
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - setuptools==72.1.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.37
      - starlette==0.45.2
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - tomlkit==0.13.2
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - torchelastic==0.2.2
      - torchmetrics==1.6.1
      - tornado==6.4.2
      - tqdm_joblib==0.0.4
      - transformers==4.48.1
      - triton==3.1.0
      - typer==0.15.1
      - types-dataclasses==0.6.6
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.1
      - uri-template==1.3.0
      - uvicorn==0.34.0
      - wandb==0.19.4
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==14.2
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - xxhash==3.5.0
      - yarl==1.18.3
